### ISSUE TITLE
How to utilize this from scratch?

### ISSUE THREAD

**Issue by ajmalafif** [Availity/design-tokens#62]
Hi there,

First of all, I want to say thank you for this repo and the [Medium post](https://medium.com/@dznjudo/piping-design-tokens-from-figma-8a086a6ac17c). 

I was trying to figure out, let say I am starting from scratch and know upfront I will be using Tailwind for my CSS library. So instead of starting via Figma (with Tailwind Figma Project File from Community), I was thinking best if I could start with Tailwind preset/default config instead. 

So here is what I did:
1. I clone this repo
2. I go to Figma Tokens plugin; `Load` -> `File` -> `Choose File` and chose `tokens.json`

And now I have the tokens loaded on Figma Tokens. However, I noticed that the say for properties like `line-height` in the Figma Tokens is different from the one in Tailwind docs (example below).

Am I missing a step here or approaching this wrongly?

<img width="546" alt="CleanShot 2022-09-10 at 22 54 43@2x" src="https://user-images.githubusercontent.com/827167/189488927-89961371-d633-434a-a121-d15802104fd5.png">
<img width="777" alt="CleanShot 2022-09-10 at 22 55 34@2x" src="https://user-images.githubusercontent.com/827167/189488937-0783aa34-f795-4920-ae0c-d034f9b3488e.png">

**Comment by dznjudo** [comment]
Correct you would just need to build your tokens from scratch and match the format tailwind uses
